# Generated by Django 4.2.5 on 2023-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_pdf',
            field=models.FileField(null=True, upload_to='prescription_pdf'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_images',
            field=models.ImageField(null=True, upload_to='prescription_images'),
        ),
    ]
