# Generated by Django 4.2.5 on 2023-10-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_prescription_prescription_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_images',
            field=models.ImageField(blank=True, null=True, upload_to='prescription_images'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_pdf',
            field=models.FileField(blank=True, null=True, upload_to='prescription_pdf'),
        ),
    ]
