# Generated by Django 4.2.5 on 2023-12-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_prescription_prescription_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')], max_length=10),
        ),
    ]
