# Generated by Django 4.2.5 on 2023-10-03 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_prescription'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='Item',
            field=models.ForeignKey(null='False', on_delete=django.db.models.deletion.CASCADE, to='item.item'),
            preserve_default='False',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
