# Generated by Django 4.2.5 on 2023-10-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_prescription'),
        ('cart', '0002_remove_cartitem_product_cartitem_item_delete_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'Item')},
        ),
    ]
