# Generated by Django 4.2.5 on 2023-10-04 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('cartitem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem')),
            ],
        ),
    ]
