# Generated by Django 4.2.5 on 2023-10-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_checkoutdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
