# Generated by Django 4.2.5 on 2023-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_rename_fistname_checkoutdetails_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutdetails',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='checkoutdetails',
            name='phoneNumber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='checkoutdetails',
            name='postalcode',
            field=models.CharField(max_length=7),
        ),
    ]
