# Generated by Django 4.2.5 on 2023-12-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_checkoutdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdetails',
            name='country',
            field=models.CharField(default='India', max_length=20),
        ),
    ]
